version: "3.8"

services:
  directus:
    container_name: directus
    build:
      context: "./directus/"
      dockerfile: Dockerfile
    ports:
      - "8055:8055"
    volumes:
      - ./uploads:/directus/uploads
    networks:
      - directus
    secrets:
      - supabase_db_user
      - supabase_db_password
      - supabase_db_name
      - supabase_host
    environment:
      DB_CLIENT: "pg"
      DB_HOST_FILE: "/run/secrets/supabase_host"
      DB_PORT: "5432"
      DB_DATABASE_FILE: "/run/secrets/supabase_db_name"
      DB_USER_FILE: "/run/secrets/supabase_db_user"
      DB_PASSWORD_FILE: "/run/secrets/supabase_db_password"
      DB_SSL: "true"                               # Enable SSL for DB connection
      DB_SSL__REJECT_UNAUTHORIZED: "true"          # Enforce certificate validation
      DB_SSL_CA_FILE: "/run/secrets/supabase_ca"   # Path to CA certificate (optional)
      PUBLIC_URL: "https://content.grile.ro"

networks:
  directus:

secrets:
  supabase_db_user:
    external: true
  supabase_db_password:
    external: true
  supabase_db_name:
    external: true
  supabase_host:
    external: true
  supabase_ca:
    external: true  # Add CA certificate as a secret if needed
